name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add a build step to compile your React components into static files
      - name: Build
        run: |
          npm install # Or any other commands needed to build your project
          npm run build # Assuming your build script is defined in package.json

      # Copy the built files to a temporary directory
      - name: Copy files
        run: |
          mkdir deploy
          cp -r ./build/* ./deploy

      # Deploy the built files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
